### PR TITLE
added german translation

### PR DESCRIPTION
**Pull request by MalteKiefer**

### CODE REVIEW

**Comment by alexamiryan** [comment]
Thanks @MalteKiefer for the german translation. Will merge that. However just wanted to ask, what's up with the .gitignore file?

**Comment by MalteKiefer** [comment]
I update to the latest, from here: https://www.toptal.com/developers/gitignore
So you get really all file for Android and Android Studio

**Comment by alexamiryan** [comment]
Thanks

**Comment by MalteKiefer** [comment]
Thank sou for that amazing app.
Hope there is a Linux client soon.

**Comment by MalteKiefer** [comment]
@alexamiryan do you want to merge it?

**Comment by alexamiryan** [comment]
Sure, will merge this today

**Review by alexamiryan — APPROVED** [review]

**Pull request merged**
